'''
A dictionary of common compounds keyed to the english name as a string.
'''

compound = {}

compound["ammonium"] = "NH4+1"
compound["perchlorate"] = "ClO4-1"
compound["hydrogen sulfate"] = "HSO4-1"
compound["sulfate"] = "SO4-2"
compound["oxalate"] = "C2O4-2"
compound["hydronium"] = "H3O+1"
compound["chlorate"] = "ClO3-1"
compound["sulfite"] = "SO3-2"
compound["silicate"] = "SiO3-2"
compound["acetate"] = "C2H3O2-1"
compound["chlorite"] = "ClO2-1"
compound["permanganate"] = "MnO4-1"
compound["phthalate"] = "C8H4O4-2"
compound["peroxide"] = "O2-2"
compound["acetate ion"] = "CH3COO-1"
compound["hypochlorite"] = "ClO-1"
compound["periodate"] = "IO4-1"
compound["chromate"] = "CrO4-2"
compound["tetraborate"] = "B4O7-2"
compound["hydroxide"] = "OH-1"
compound["nitrate"] = "NO3-1"
compound["hydrogen carbonate"] = "HCO3-1"
compound["dichromate"] = "Cr2O7-2"
compound["borate"] = "BO3-3"
compound["cyanide"] = "CN-1"
compound["nitrite"] = "NO2-1"
compound["carbonate"] = "CO3-2"
compound["arsenate"] = "AsO4-3"
compound["cyanate"] = "OCN-1"
compound["bromate"] = "BrO3-1"
compound["dihydrogen phosphate"] = "H2PO4-1"
compound["hydrogen phosphate"] = "HPO4-2"
compound["phosphate"] = "PO4-3"
compound["thiocyanate"] = "SCN-1"
compound["iodate"] = "IO3-1"
compound["orthosilicate"] = "SiO4-4"
